"new master"

diff --git a/leaks b/leaks
--- a/leaks
+++ b/leaks
@@ -1,3 +1,5 @@
+#!/bin/bash
+
 while :
 do
     echo -n "Enter the program name to run (or 'q' to quit): "
@@ -10,9 +12,10 @@ do
     # 실행할 프로그램 명칭으로 설정하고 실행
     $program_name
 
-	while :
-	do
-		leaks $program_name
-    	sleep 0.5
-	done
+    # 에러 체크 (리턴 코드를 사용)
+    if [ $? -ne 0 ]; then
+        echo "Error: $program_name 실행 중 오류가 발생했습니다."
+    fi
+
+    sleep 2
 done
